Version: '${project.version}'
Debug: false

# 语言文件
Language: default

# SQL参数(高一点的版本需要在url加上'useSSL=false')
Sql: false
Url: 'jdbc:mysql://localhost:3306/mc_market?useSSL=false&serverTimezone=UTC'
User: 'root'
Password: '123456'

# 周目
Season: 0
